name: wathefty
description: Wathefty.

publish_to: 'none' 

version: 1.2.3+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  http: ^0.13.4
  shared_preferences: ^2.0.13
  get: ^4.6.1
  carousel_slider: ^4.0.0
  select_form_field: ^2.2.0
  file_picker: ^4.2.7
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master 
  pull_to_refresh: ^2.0.0
  easy_localization: ^3.0.0
  firebase_analytics: ^9.1.0
  new_version: ^0.3.0
  flutter_facebook_auth: ^4.1.1
  google_sign_in: ^5.2.4
  url_launcher: ^6.0.20
  intl_phone_number_input: ^0.7.0+2
  flutter_speed_dial: ^5.0.0+1
  better_player: ^0.0.81
  flutter_rating_bar: ^4.0.0
  flutter_native_splash: ^1.3.2
  expandable: ^5.0.1
  # google_maps_flutter: ^2.1.1
  social_share: ^2.2.1
  flutter_otp_text_field: ^1.0.0
  libphonenumber: ^2.0.2
  onesignal_flutter: ^3.2.8
  multi_select_flutter: ^4.0.0
  dropdown_search: ^2.0.1
  # logger: ^1.1.0
  sign_in_with_apple: ^3.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/



flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  # flutter pub run flutter_native_splash:remove  
  # color or background_image is the only required parameter.  Use color to set the background
  # color: "#42618a"
  color: "#FFFFFF"
  #background_image: "assets/background.png"
  image: assets/logo_blue.png
  # color_dark: "#172436"
  color_dark: "#000000"
  image_dark: assets/logo_blue.png