var countryArr = [
  {"id": 1, "name_en": "Andorra", "name_ar": "أندورا"},
  {"id": 2, "name_en": "United Arab Emirates", "name_ar": "الإمارات العربية المتحدة"},
  {"id": 3, "name_en": "Afghanistan", "name_ar": "أفغانستان"},
  {"id": 4, "name_en": "Antigua and Barbuda", "name_ar": "أنتيغوا وباربودا"},
  {"id": 5, "name_en": "Anguilla", "name_ar": "أنغويلا"},
  {"id": 6, "name_en": "Albania", "name_ar": "ألبانيا"},
  {"id": 7, "name_en": "Armenia", "name_ar": "أرمينيا"},
  {"id": 8, "name_en": "Angola", "name_ar": "أنغولا"},
  {"id": 9, "name_en": "Antarctica", "name_ar": "القارة القطبية الجنوبية"},
  {"id": 10, "name_en": "Argentina", "name_ar": "الأرجنتين"},
  {"id": 11, "name_en": "American Samoa", "name_ar": "ساموا الأمريكية"},
  {"id": 12, "name_en": "Austria", "name_ar": "النمسا"},
  {"id": 13, "name_en": "Australia", "name_ar": "أستراليا"},
  {"id": 14, "name_en": "Aruba", "name_ar": "أروبا"},
  {"id": 15, "name_en": "Aland Islands", "name_ar": "جزر أولاند"},
  {"id": 16, "name_en": "Azerbaijian", "name_ar": "أذربيجان"},
  {"id": 17, "name_en": "Bosnia and Herzegovina", "name_ar": "البوسنة والهرسك"},
  {"id": 18, "name_en": "Barbados", "name_ar": "باربادوس"},
  {"id": 19, "name_en": "Bangladesh", "name_ar": "بنغلاديش"},
  {"id": 20, "name_en": "Belgium", "name_ar": "بلجيكا"},
  {"id": 21, "name_en": "Burkina Faso", "name_ar": "بوركينا فاسو"},
  {"id": 22, "name_en": "Bulgaria", "name_ar": "بلغاريا"},
  {"id": 23, "name_en": "Bahrain", "name_ar": "البحرين"},
  {"id": 24, "name_en": "Burundi", "name_ar": "بوروندي"},
  {"id": 25, "name_en": "Benin", "name_ar": "بنين"},
  {"id": 26, "name_en": "Saint Barthelemy", "name_ar": "سان بارتيلمي"},
  {"id": 27, "name_en": "Bermuda", "name_ar": "برمودا"},
  {"id": 28, "name_en": "Brunei Darussalam", "name_ar": "بروناي"},
  {"id": 29, "name_en": "Bolivia (Plurinational State of)", "name_ar": "بوليفيا"},
  {"id": 30, "name_en": "Bonaire, Sint Eustatius and Saba", "name_ar": "الجزر الكاريبية الهولندية"},
  {"id": 31, "name_en": "Brazil", "name_ar": "البرازيل"},
  {"id": 32, "name_en": "Bahamas", "name_ar": "باهاماس"},
  {"id": 33, "name_en": "Bhutan", "name_ar": "بوتان"},
  {"id": 34, "name_en": "Botswana", "name_ar": "بوتسوانا"},
  {"id": 35, "name_en": "Belarus", "name_ar": "روسيا البيضاء"},
  {"id": 36, "name_en": "Belize", "name_ar": "بليز"},
  {"id": 37, "name_en": "Canada", "name_ar": "كندا"},
  {"id": 38, "name_en": "Cocos (Keeling) Islands", "name_ar": "جزر كوكوس"},
  {"id": 39, "name_en": "Congo (the Democratic Republic of the)", "name_ar": "جمهورية الكونغو الديمقراطية"},
  {"id": 40, "name_en": "Central African Republic", "name_ar": "جمهورية أفريقيا الوسطى"},
  {"id": 41, "name_en": "Congo", "name_ar": "كونغو (توضيح)"},
  {"id": 42, "name_en": "Switzerland", "name_ar": "سويسرا"},
  {"id": 43, "name_en": "Cote D'ivoire", "name_ar": "ساحل العاج"},
  {"id": 44, "name_en": "Cook Islands", "name_ar": "جزر كوك"},
  {"id": 45, "name_en": "Chile", "name_ar": "تشيلي"},
  {"id": 46, "name_en": "Cameroon", "name_ar": "الكاميرون"},
  {"id": 47, "name_en": "China", "name_ar": "الصين"},
  {"id": 48, "name_en": "Colombia", "name_ar": "كولومبيا"},
  {"id": 49, "name_en": "Costa Rica", "name_ar": "كوستاريكا"},
  {"id": 50, "name_en": "Cuba", "name_ar": "كوبا"},
  {"id": 51, "name_en": "Cabo Verde", "name_ar": "الرأس الأخضر"},
  {"id": 52, "name_en": "Curacao", "name_ar": "كوراساو"},
  {"id": 53, "name_en": "Christmas Island", "name_ar": "جزيرة كريسماس"},
  {"id": 54, "name_en": "Cyprus", "name_ar": "قبرص"},
  {"id": 55, "name_en": "Czechia", "name_ar": "التشيك"},
  {"id": 56, "name_en": "Germany", "name_ar": "ألمانيا"},
  {"id": 57, "name_en": "Djibouti", "name_ar": "جيبوتي"},
  {"id": 58, "name_en": "Denmark", "name_ar": "الدنمارك"},
  {"id": 59, "name_en": "Dominica", "name_ar": "دومينيكا"},
  {"id": 60, "name_en": "Dominican Republic", "name_ar": "جمهورية الدومينيكان"},
  {"id": 61, "name_en": "Algeria", "name_ar": "الجزائر"},
  {"id": 62, "name_en": "Ecuador", "name_ar": "الإكوادور"},
  {"id": 63, "name_en": "Estonia", "name_ar": "إستونيا"},
  {"id": 64, "name_en": "Egypt", "name_ar": "مصر"},
  {"id": 65, "name_en": "Western Sahara", "name_ar": "الصحراء الغربية"},
  {"id": 66, "name_en": "Eritrea", "name_ar": "إريتريا"},
  {"id": 67, "name_en": "Spain", "name_ar": "إسبانيا"},
  {"id": 68, "name_en": "Ethiopia", "name_ar": "إثيوبيا"},
  {"id": 69, "name_en": "Finland", "name_ar": "فنلندا"},
  {"id": 70, "name_en": "Fiji", "name_ar": "فيجي"},
  {"id": 71, "name_en": "Falkland Islands (Malvinas)", "name_ar": "جزر فوكلاند"},
  {"id": 72, "name_en": "Micronesia (Federated States of)", "name_ar": "ولايات ميكرونيسيا المتحدة"},
  {"id": 73, "name_en": "Faroe Islands", "name_ar": "جزر فارو"},
  {"id": 74, "name_en": "France", "name_ar": "فرنسا"},
  {"id": 75, "name_en": "Gabon", "name_ar": "الغابون"},
  {"id": 76, "name_en": "United Kingdom of Great Britain and Northern Ireland", "name_ar": "المملكة المتحدة"},
  {"id": 77, "name_en": "Grenada", "name_ar": "غرينادا"},
  {"id": 78, "name_en": "Georgia", "name_ar": "جورجيا (توضيح)"},
  {"id": 79, "name_en": "French Guiana", "name_ar": "غويانا الفرنسية"},
  {"id": 80, "name_en": "Guernsey", "name_ar": "غيرنسي"},
  {"id": 81, "name_en": "Ghana", "name_ar": "غانا"},
  {"id": 82, "name_en": "Gibraltar", "name_ar": "جبل طارق"},
  {"id": 83, "name_en": "Greenland", "name_ar": "جرينلاند"},
  {"id": 84, "name_en": "Gambia", "name_ar": "غامبيا"},
  {"id": 85, "name_en": "Guinea", "name_ar": "غينيا"},
  {"id": 86, "name_en": "Guadeloupe", "name_ar": "غوادلوب"},
  {"id": 87, "name_en": "Equatorial Guinea", "name_ar": "غينيا الاستوائية"},
  {"id": 88, "name_en": "Greece", "name_ar": "اليونان"},
  {"id": 89, "name_en": "South Georgia and The South Sandwich Islands", "name_ar": "جورجيا الجنوبية وجزر ساندويتش الجنوبية"},
  {"id": 90, "name_en": "Guatemala", "name_ar": "غواتيمالا"},
  {"id": 91, "name_en": "Guam", "name_ar": "غوام"},
  {"id": 92, "name_en": "Guinea-Bissau", "name_ar": "غينيا بيساو"},
  {"id": 93, "name_en": "Guyana", "name_ar": "غيانا"},
  {"id": 94, "name_en": "Hong Kong", "name_ar": "هونغ كونغ"},
  {"id": 95, "name_en": "Honduras", "name_ar": "هندوراس"},
  {"id": 96, "name_en": "Croatia", "name_ar": "كرواتيا"},
  {"id": 97, "name_en": "Haiti", "name_ar": "هايتي"},
  {"id": 98, "name_en": "Hungary", "name_ar": "المجر"},
  {"id": 99, "name_en": "Indonesia", "name_ar": "إندونيسيا"},
  {"id": 100, "name_en": "Ireland", "name_ar": "جزيرة أيرلندا"},
  {"id": 101, "name_en": "Israel", "name_ar": "إسرائيل"},
  {"id": 102, "name_en": "Isle of Man", "name_ar": "جزيرة مان"},
  {"id": 103, "name_en": "India", "name_ar": "الهند"},
  {"id": 104, "name_en": "British Indian Ocean Territory", "name_ar": "إقليم المحيط الهندي البريطاني"},
  {"id": 105, "name_en": "Iraq", "name_ar": "العراق"},
  {"id": 106, "name_en": "Iran (Islamic Republic of)", "name_ar": "إيران"},
  {"id": 107, "name_en": "Iceland", "name_ar": "آيسلندا"},
  {"id": 108, "name_en": "Italy", "name_ar": "إيطاليا"},
  {"id": 109, "name_en": "Jersey", "name_ar": "جيرزي"},
  {"id": 110, "name_en": "Jamaica", "name_ar": "جامايكا"},
  {"id": 111, "name_en": "Jordan", "name_ar": "الأردن"},
  {"id": 112, "name_en": "Japan", "name_ar": "اليابان"},
  {"id": 113, "name_en": "Kenya", "name_ar": "كينيا"},
  {"id": 114, "name_en": "Kyrgyzstan", "name_ar": "قيرغيزستان"},
  {"id": 115, "name_en": "Cambodia", "name_ar": "كمبوديا"},
  {"id": 116, "name_en": "Kiribati", "name_ar": "كيريباتي"},
  {"id": 117, "name_en": "Comoros", "name_ar": "جزر القمر"},
  {"id": 118, "name_en": "Saint Kitts and Nevis", "name_ar": "سانت كيتس ونيفيس"},
  {"id": 119, "name_en": "Korea (the Democratic People's Republic of)", "name_ar": "كوريا الشمالية"},
  {"id": 120, "name_en": "Korea (the Republic of)", "name_ar": "كوريا الجنوبية"},
  {"id": 121, "name_en": "Kuwait", "name_ar": "الكويت"},
  {"id": 122, "name_en": "Cayman Islands", "name_ar": "جزر كايمان"},
  {"id": 123, "name_en": "Kazakhstan", "name_ar": "كازاخستان"},
  {"id": 124, "name_en": "Lao People's Democratic Republic", "name_ar": "لاوس"},
  {"id": 125, "name_en": "Lebanon", "name_ar": "لبنان"},
  {"id": 126, "name_en": "Saint Lucia", "name_ar": "سانت لوسيا"},
  {"id": 127, "name_en": "Liechtenstein", "name_ar": "ليختنشتاين"},
  {"id": 128, "name_en": "Sri Lanka", "name_ar": "سريلانكا"},
  {"id": 129, "name_en": "Liberia", "name_ar": "ليبيريا"},
  {"id": 130, "name_en": "Lesotho", "name_ar": "ليسوتو"},
  {"id": 131, "name_en": "Lithuania", "name_ar": "ليتوانيا"},
  {"id": 132, "name_en": "Luxembourg", "name_ar": "لوكسمبورغ"},
  {"id": 133, "name_en": "Latvia", "name_ar": "لاتفيا"},
  {"id": 134, "name_en": "Libya", "name_ar": "ليبيا"},
  {"id": 135, "name_en": "Morocco", "name_ar": "المغرب"},
  {"id": 136, "name_en": "Monaco", "name_ar": "موناكو"},
  {"id": 137, "name_en": "Moldova (the Republic of)", "name_ar": "مولدوفا"},
  {"id": 138, "name_en": "Montenegro", "name_ar": "الجبل الأسود"},
  {"id": 139, "name_en": "Saint Martin (French Part)", "name_ar": "تجمع سان مارتين"},
  {"id": 140, "name_en": "Madagascar", "name_ar": "مدغشقر"},
  {"id": 141, "name_en": "Marshall Islands", "name_ar": "جزر مارشال"},
  {"id": 142, "name_en": "North Macedonia", "name_ar": "جمهورية مقدونيا"},
  {"id": 143, "name_en": "Mali", "name_ar": "مالي"},
  {"id": 144, "name_en": "Myanmar", "name_ar": "ميانمار"},
  {"id": 145, "name_en": "Mongolia", "name_ar": "منغوليا"},
  {"id": 146, "name_en": "Macao", "name_ar": "ماكاو"},
  {"id": 147, "name_en": "Northern Mariana Islands", "name_ar": "جزر ماريانا الشمالية"},
  {"id": 148, "name_en": "Martinique", "name_ar": "مارتينيك"},
  {"id": 149, "name_en": "Mauritania", "name_ar": "موريتانيا"},
  {"id": 150, "name_en": "Montserrat", "name_ar": "مونتسرات"},
  {"id": 151, "name_en": "Malta", "name_ar": "مالطا"},
  {"id": 152, "name_en": "Mauritius", "name_ar": "موريشيوس"},
  {"id": 153, "name_en": "Maldives", "name_ar": "المالديف"},
  {"id": 154, "name_en": "Malawi", "name_ar": "مالاوي"},
  {"id": 155, "name_en": "Mexico", "name_ar": "المكسيك"},
  {"id": 156, "name_en": "Malaysia", "name_ar": "ماليزيا"},
  {"id": 157, "name_en": "Mozambique", "name_ar": "موزمبيق"},
  {"id": 158, "name_en": "Namibia", "name_ar": "ناميبيا"},
  {"id": 159, "name_en": "New Caledonia", "name_ar": "كاليدونيا الجديدة"},
  {"id": 160, "name_en": "Niger", "name_ar": "النيجر"},
  {"id": 161, "name_en": "Norfolk Island", "name_ar": "جزيرة نورفولك"},
  {"id": 162, "name_en": "Nigeria", "name_ar": "نيجيريا"},
  {"id": 163, "name_en": "Nicaragua", "name_ar": "نيكاراغوا"},
  {"id": 164, "name_en": "Netherlands", "name_ar": "هولندا"},
  {"id": 165, "name_en": "Norway", "name_ar": "النرويج"},
  {"id": 166, "name_en": "Nepal", "name_ar": "نيبال"},
  {"id": 167, "name_en": "Nauru", "name_ar": "ناورو"},
  {"id": 168, "name_en": "Niue", "name_ar": "نييوي"},
  {"id": 169, "name_en": "New Zealand", "name_ar": "نيوزيلندا"},
  {"id": 170, "name_en": "Oman", "name_ar": "سلطنة عمان"},
  {"id": 171, "name_en": "Panama", "name_ar": "بنما"},
  {"id": 172, "name_en": "Peru", "name_ar": "بيرو"},
  {"id": 173, "name_en": "French Polynesia", "name_ar": "بولينزيا الفرنسية"},
  {"id": 174, "name_en": "Papua New Guinea", "name_ar": "بابوا غينيا الجديدة"},
  {"id": 175, "name_en": "Philippines", "name_ar": "الفلبين"},
  {"id": 176, "name_en": "Pakistan", "name_ar": "باكستان"},
  {"id": 177, "name_en": "Poland", "name_ar": "بولندا"},
  {"id": 178, "name_en": "Saint Pierre and Miquelon", "name_ar": "سان بيير وميكلون"},
  {"id": 179, "name_en": "Pitcairn", "name_ar": "جزر بيتكيرن"},
  {"id": 180, "name_en": "Puerto Rico", "name_ar": "بورتوريكو"},
  {"id": 181, "name_en": "Palestine, State of", "name_ar": "دولة فلسطين"},
  {"id": 182, "name_en": "Portugal", "name_ar": "البرتغال"},
  {"id": 183, "name_en": "Palau", "name_ar": "بالاو"},
  {"id": 184, "name_en": "Paraguay", "name_ar": "باراغواي"},
  {"id": 185, "name_en": "Qatar", "name_ar": "قطر"},
  {"id": 186, "name_en": "Reunion", "name_ar": "لا ريونيون"},
  {"id": 187, "name_en": "Romania", "name_ar": "رومانيا"},
  {"id": 188, "name_en": "Serbia", "name_ar": "صربيا"},
  {"id": 189, "name_en": "Russian Federation", "name_ar": "روسيا"},
  {"id": 190, "name_en": "Rwanda", "name_ar": "رواندا"},
  {"id": 191, "name_en": "Saudi Arabia", "name_ar": "السعودية"},
  {"id": 192, "name_en": "Solomon Islands", "name_ar": "جزر سليمان"},
  {"id": 193, "name_en": "Seychelles", "name_ar": "سيشل"},
  {"id": 194, "name_en": "Sudan", "name_ar": "السودان"},
  {"id": 195, "name_en": "Sweden", "name_ar": "السويد"},
  {"id": 196, "name_en": "Singapore", "name_ar": "سنغافورة"},
  {"id": 197, "name_en": "Saint Helena, Ascension and Tristan Da Cunha", "name_ar": "سانت هيلانة وأسينشين وتريستان دا كونا"},
  {"id": 198, "name_en": "Slovenia", "name_ar": "سلوفينيا"},
  {"id": 199, "name_en": "Svalbard and Jan Mayen", "name_ar": "سفالبارد ويان ماين"},
  {"id": 200, "name_en": "Slovakia", "name_ar": "سلوفاكيا"},
  {"id": 201, "name_en": "Sierra Leone", "name_ar": "سيراليون"},
  {"id": 202, "name_en": "San Marino", "name_ar": "سان مارينو"},
  {"id": 203, "name_en": "Senegal", "name_ar": "السنغال"},
  {"id": 204, "name_en": "Somalia", "name_ar": "الصومال"},
  {"id": 205, "name_en": "Suriname", "name_ar": "سورينام"},
  {"id": 206, "name_en": "South Sudan", "name_ar": "جنوب السودان"},
  {"id": 207, "name_en": "Sao Tome and Principe", "name_ar": "ساو تومي وبرينسيب"},
  {"id": 208, "name_en": "El Salvador", "name_ar": "السلفادور"},
  {"id": 209, "name_en": "Sint Maarten (Dutch Part)", "name_ar": "سينت مارتن"},
  {"id": 210, "name_en": "Syrian Arab Republic", "name_ar": "سوريا"},
  {"id": 211, "name_en": "Eswatini", "name_ar": "إسواتيني"},
  {"id": 212, "name_en": "Turks and Caicos Islands", "name_ar": "جزر توركس وكايكوس"},
  {"id": 213, "name_en": "Chad", "name_ar": "تشاد"},
  {"id": 214, "name_en": "French Southern Territories", "name_ar": "أراض فرنسية جنوبية وأنتارتيكية"},
  {"id": 215, "name_en": "Togo", "name_ar": "توغو"},
  {"id": 216, "name_en": "Thailand", "name_ar": "تايلاند"},
  {"id": 217, "name_en": "Tajikistan", "name_ar": "طاجيكستان"},
  {"id": 218, "name_en": "Tokelau", "name_ar": "توكيلاو"},
  {"id": 219, "name_en": "Timor-Leste", "name_ar": "تيمور الشرقية"},
  {"id": 220, "name_en": "Turkmenistan", "name_ar": "تركمانستان"},
  {"id": 221, "name_en": "Tunisia", "name_ar": "تونس"},
  {"id": 222, "name_en": "Tonga", "name_ar": "تونغا"},
  {"id": 223, "name_en": "Turkey", "name_ar": "تركيا"},
  {"id": 224, "name_en": "Trinidad and Tobago", "name_ar": "ترينيداد وتوباغو"},
  {"id": 225, "name_en": "Tuvalu", "name_ar": "توفالو"},
  {"id": 226, "name_en": "Taiwan (Province of China)", "name_ar": "تايوان"},
  {"id": 227, "name_en": "Tanzania, United Republic of", "name_ar": "تنزانيا"},
  {"id": 228, "name_en": "Ukraine", "name_ar": "أوكرانيا"},
  {"id": 229, "name_en": "Uganda", "name_ar": "أوغندا"},
  {"id": 230, "name_en": "United States Minor Outlying Islands", "name_ar": "جزر الولايات المتحدة الصغيرة النائية"},
  {"id": 231, "name_en": "United States of America", "name_ar": "الولايات المتحدة"},
  {"id": 232, "name_en": "Uruguay", "name_ar": "الأوروغواي"},
  {"id": 233, "name_en": "Uzbekistan", "name_ar": "أوزبكستان"},
  {"id": 234, "name_en": "Holy See", "name_ar": "الكرسي الرسولي"},
  {"id": 235, "name_en": "Saint Vincent and The Grenadines", "name_ar": "سانت فينسنت والغرينادين"},
  {"id": 236, "name_en": "Venezuela (Bolivarian Republic of)", "name_ar": "فنزويلا"},
  {"id": 237, "name_en": "Virgin Islands (British)", "name_ar": "جزر العذراء البريطانية"},
  {"id": 238, "name_en": "Virgin Islands (U.S.)", "name_ar": "جزر العذراء الأمريكية"},
  {"id": 239, "name_en": "Viet Nam", "name_ar": "فيتنام"},
  {"id": 240, "name_en": "Vanuatu", "name_ar": "فانواتو"},
  {"id": 241, "name_en": "Wallis and Futuna", "name_ar": "واليس وفوتونا"},
  {"id": 242, "name_en": "Samoa", "name_ar": "ساموا"},
  {"id": 243, "name_en": "Yemen", "name_ar": "اليمن"},
  {"id": 244, "name_en": "Mayotte", "name_ar": "مايوت"},
  {"id": 245, "name_en": "South Africa", "name_ar": "جنوب أفريقيا"},
  {"id": 246, "name_en": "Zambia", "name_ar": "زامبيا"},
  {"id": 247, "name_en": "Zimbabwe", "name_ar": "زيمبابوي"}
];
var companyCategoryArr = [
  {'id': 1, "name_en": 'Governmental Institution', "name_ar": 'مؤسسة حكومية'},
  {'id': 2, "name_en": 'Individual Foundation', "name_ar": 'مؤسسة فردية'},
  {'id': 3, "name_en": 'Shops', "name_ar": 'محلات'},
  {'id': 4, "name_en": 'Civil Society Organization', "name_ar": 'مؤسسة مجتمع  مدني'},
  {'id': 5, "name_en": 'L.L.C', "name_ar": 'ذ.م.م'},
  {'id': 6, "name_en": 'Simple Recommendation Companies', "name_ar": 'شركات التوصية البسيطة'},
];
var companyCapacityArr = [
  {'id': 1, "name_en": 'Individual Foundation', "name_ar": 'مؤسسة فردية'},
  {'id': 2, "name_en": 'Shops', "name_ar": 'محلات'},
  {'id': 3, "name_en": 'Training Institutions', "name_ar": 'مؤسسات تدريبية'},
  {'id': 4, "name_en": 'Not wholly Owned By The Government', "name_ar": 'حكومية غير مملوكة بالكامل'},
  {'id': 5, "name_en": 'Wholly Owned Government', "name_ar": 'حكومية مملوكة بالكامل'},
  {'id': 6, "name_en": 'Private company', "name_ar": 'شركة خاصة'},
  {'id': 7, "name_en": 'Civil Society Organization', "name_ar": 'مؤسسة مجتمع  مدني'},
];
var companySizeArr = [
  {'id': 1, "name_en": 'Multinational Company', "name_ar": 'شركة متعددة الجنسيات'},
  {'id': 2, "name_en": 'International Organizations', "name_ar": 'منظمات دولية'},
  {'id': 3, "name_en": 'Big Company', "name_ar": 'شركة كبرى'},
  {'id': 4, "name_en": 'Medium Companies', "name_ar": 'شركات متوسطة'},
];
final List<Map<String, dynamic>> numbers = [
  {'value': "0"},
  {'value': "1"},
  {'value': "2"},
  {'value': "3"},
  {'value': "4"},
  {'value': "5"},
  {'value': "6"},
  {'value': "7"},
  {'value': "8"},
  {'value': "9"},
  {'value': "10"},
  {'value': "11"},
  {'value': "12"},
  {'value': "13"},
  {'value': "14"},
  {'value': "15"},
  {'value': "16"},
  {'value': "17"},
  {'value': "18"},
  {'value': "19"},
  {'value': "20"},
  {'value': "21"},
  {'value': "22"},
  {'value': "23"},
  {'value': "24"},
  {'value': "25"},
  {'value': "26"},
  {'value': "27"},
  {'value': "28"},
  {'value': "29"},
  {'value': "30"},
  {'value': "31"},
  {'value': "32"},
  {'value': "33"},
  {'value': "34"},
  {'value': "35"},
  {'value': "36"},
  {'value': "37"},
  {'value': "38"},
  {'value': "39"},
  {'value': "40"},
  {'value': "41"},
  {'value': "42"},
  {'value': "43"},
  {'value': "44"},
  {'value': "45"},
  {'value': "46"},
  {'value': "47"},
  {'value': "48"},
  {'value': "49"},
  {'value': "50"},
  {'value': "51"},
  {'value': "52"},
  {'value': "53"},
  {'value': "54"},
  {'value': "55"},
  {'value': "56"},
  {'value': "57"},
  {'value': "58"},
  {'value': "59"},
  {'value': "60"}
];
List nationalityArr = [
  {"id": 1, "name_en": "Afghan", "name_ar": "أفغانستاني", "code": "AF"},
  {"id": 2, "name_en": "Albanian", "name_ar": "ألباني", "code": "AL"},
  {"id": 3, "name_en": "Aland Islander", "name_ar": "آلاندي", "code": "AX"},
  {"id": 4, "name_en": "Algerian", "name_ar": "جزائري", "code": "DZ"},
  {"id": 5, "name_en": "American Samoan", "name_ar": "أمريكي سامواني", "code": "AS"},
  {"id": 6, "name_en": "Andorran", "name_ar": "أندوري", "code": "AD"},
  {"id": 7, "name_en": "Angolan", "name_ar": "أنقولي", "code": "AO"},
  {"id": 8, "name_en": "Anguillan", "name_ar": "أنغويلي", "code": "AI"},
  {"id": 9, "name_en": "Antarctican", "name_ar": "أنتاركتيكي", "code": "AQ"},
  {"id": 10, "name_en": "Antiguan", "name_ar": "بربودي", "code": "AG"},
  {"id": 11, "name_en": "Argentinian", "name_ar": "أرجنتيني", "code": "AR"},
  {"id": 12, "name_en": "Armenian", "name_ar": "أرميني", "code": "AM"},
  {"id": 13, "name_en": "Aruban", "name_ar": "أوروبهيني", "code": "AW"},
  {"id": 14, "name_en": "Australian", "name_ar": "أسترالي", "code": "AU"},
  {"id": 15, "name_en": "Austrian", "name_ar": "نمساوي", "code": "AT"},
  {"id": 16, "name_en": "Azerbaijani", "name_ar": "أذربيجاني", "code": "AZ"},
  {"id": 17, "name_en": "Bahamian", "name_ar": "باهاميسي", "code": "BS"},
  {"id": 18, "name_en": "Bahraini", "name_ar": "بحريني", "code": "BH"},
  {"id": 19, "name_en": "Bangladeshi", "name_ar": "بنغلاديشي", "code": "BD"},
  {"id": 20, "name_en": "Barbadian", "name_ar": "بربادوسي", "code": "BB"},
  {"id": 21, "name_en": "Belarusian", "name_ar": "روسي", "code": "BY"},
  {"id": 22, "name_en": "Belgian", "name_ar": "بلجيكي", "code": "BE"},
  {"id": 23, "name_en": "Belizean", "name_ar": "بيليزي", "code": "BZ"},
  {"id": 24, "name_en": "Beninese", "name_ar": "بنيني", "code": "BJ"},
  {"id": 25, "name_en": "Saint Barthelmian", "name_ar": "سان بارتيلمي", "code": "BL"},
  {"id": 26, "name_en": "Bermudan", "name_ar": "برمودي", "code": "BM"},
  {"id": 27, "name_en": "Bhutanese", "name_ar": "بوتاني", "code": "BT"},
  {"id": 28, "name_en": "Bolivian", "name_ar": "بوليفي", "code": "BO"},
  {"id": 29, "name_en": "Bosnian / Herzegovinian", "name_ar": "بوسني/هرسكي", "code": "BA"},
  {"id": 30, "name_en": "Botswanan", "name_ar": "بوتسواني", "code": "BW"},
  {"id": 31, "name_en": "Bouvetian", "name_ar": "بوفيهي", "code": "BV"},
  {"id": 32, "name_en": "Brazilian", "name_ar": "برازيلي", "code": "BR"},
  {"id": 33, "name_en": "British Indian Ocean Territory", "name_ar": "إقليم المحيط الهندي البريطاني", "code": "IO"},
  {"id": 34, "name_en": "Bruneian", "name_ar": "بروني", "code": "BN"},
  {"id": 35, "name_en": "Bulgarian", "name_ar": "بلغاري", "code": "BG"},
  {"id": 36, "name_en": "Burkinabe", "name_ar": "بوركيني", "code": "BF"},
  {"id": 37, "name_en": "Burundian", "name_ar": "بورونيدي", "code": "BI"},
  {"id": 38, "name_en": "Cambodian", "name_ar": "كمبودي", "code": "KH"},
  {"id": 39, "name_en": "Cameroonian", "name_ar": "كاميروني", "code": "CM"},
  {"id": 40, "name_en": "Canadian", "name_ar": "كندي", "code": "CA"},
  {"id": 41, "name_en": "Cape Verdean", "name_ar": "الرأس الأخضر", "code": "CV"},
  {"id": 42, "name_en": "Caymanian", "name_ar": "كايماني", "code": "KY"},
  {"id": 43, "name_en": "Central African", "name_ar": "أفريقي", "code": "CF"},
  {"id": 44, "name_en": "Chadian", "name_ar": "تشادي", "code": "TD"},
  {"id": 45, "name_en": "Chilean", "name_ar": "شيلي", "code": "CL"},
  {"id": 46, "name_en": "Chinese", "name_ar": "صيني", "code": "CN"},
  {"id": 47, "name_en": "Christmas Islander", "name_ar": "جزيرة عيد الميلاد", "code": "CX"},
  {"id": 48, "name_en": "Cocos Islander", "name_ar": "جزر كوكوس", "code": "CC"},
  {"id": 49, "name_en": "Colombian", "name_ar": "كولومبي", "code": "CO"},
  {"id": 50, "name_en": "Comorian", "name_ar": "جزر القمر", "code": "KM"},
  {"id": 51, "name_en": "Congolese", "name_ar": "كونغي", "code": "CG"},
  {"id": 52, "name_en": "Cook Islander", "name_ar": "جزر كوك", "code": "CK"},
  {"id": 53, "name_en": "Costa Rican", "name_ar": "كوستاريكي", "code": "CR"},
  {"id": 54, "name_en": "Croatian", "name_ar": "كوراتي", "code": "HR"},
  {"id": 55, "name_en": "Cuban", "name_ar": "كوبي", "code": "CU"},
  {"id": 56, "name_en": "Cypriot", "name_ar": "قبرصي", "code": "CY"},
  {"id": 57, "name_en": "Curacian", "name_ar": "كوراساوي", "code": "CW"},
  {"id": 58, "name_en": "Czech", "name_ar": "تشيكي", "code": "CZ"},
  {"id": 59, "name_en": "Danish", "name_ar": "دنماركي", "code": "DK"},
  {"id": 60, "name_en": "Djiboutian", "name_ar": "جيبوتي", "code": "DJ"},
  {"id": 61, "name_en": "Dominican", "name_ar": "دومينيكي", "code": "DM"},
  {"id": 62, "name_en": "Dominican", "name_ar": "دومينيكي", "code": "DO"},
  {"id": 63, "name_en": "Ecuadorian", "name_ar": "إكوادوري", "code": "EC"},
  {"id": 64, "name_en": "Egyptian", "name_ar": "مصري", "code": "EG"},
  {"id": 65, "name_en": "Salvadoran", "name_ar": "سلفادوري", "code": "SV"},
  {"id": 66, "name_en": "Equatorial Guinean", "name_ar": "غيني", "code": "GQ"},
  {"id": 67, "name_en": "Eritrean", "name_ar": "إريتيري", "code": "ER"},
  {"id": 68, "name_en": "Estonian", "name_ar": "استوني", "code": "EE"},
  {"id": 69, "name_en": "Ethiopian", "name_ar": "أثيوبي", "code": "ET"},
  {"id": 70, "name_en": "Falkland Islander", "name_ar": "فوكلاندي", "code": "FK"},
  {"id": 71, "name_en": "Faroese", "name_ar": "جزر فارو", "code": "FO"},
  {"id": 72, "name_en": "Fijian", "name_ar": "فيجي", "code": "FJ"},
  {"id": 73, "name_en": "Finnish", "name_ar": "فنلندي", "code": "FI"},
  {"id": 74, "name_en": "French", "name_ar": "فرنسي", "code": "FR"},
  {"id": 75, "name_en": "French Guianese", "name_ar": "غويانا الفرنسية", "code": "GF"},
  {"id": 76, "name_en": "French Polynesian", "name_ar": "بولينيزيي", "code": "PF"},
  {"id": 77, "name_en": "French", "name_ar": "أراض فرنسية جنوبية وأنتارتيكية", "code": "TF"},
  {"id": 78, "name_en": "Gabonese", "name_ar": "غابوني", "code": "GA"},
  {"id": 79, "name_en": "Gambian", "name_ar": "غامبي", "code": "GM"},
  {"id": 80, "name_en": "Georgian", "name_ar": "جيورجي", "code": "GE"},
  {"id": 81, "name_en": "German", "name_ar": "ألماني", "code": "DE"},
  {"id": 82, "name_en": "Ghanaian", "name_ar": "غاني", "code": "GH"},
  {"id": 83, "name_en": "Gibraltar", "name_ar": "جبل طارق", "code": "GI"},
  {"id": 84, "name_en": "Guernsian", "name_ar": "غيرنزي", "code": "GG"},
  {"id": 85, "name_en": "Greek", "name_ar": "يوناني", "code": "GR"},
  {"id": 86, "name_en": "Greenlandic", "name_ar": "جرينلاندي", "code": "GL"},
  {"id": 87, "name_en": "Grenadian", "name_ar": "غرينادي", "code": "GD"},
  {"id": 88, "name_en": "Guadeloupe", "name_ar": "جزر جوادلوب", "code": "GP"},
  {"id": 89, "name_en": "Guamanian", "name_ar": "جوامي", "code": "GU"},
  {"id": 90, "name_en": "Guatemalan", "name_ar": "غواتيمالي", "code": "GT"},
  {"id": 91, "name_en": "Guinean", "name_ar": "غيني", "code": "GN"},
  {"id": 92, "name_en": "Guinea-Bissauan", "name_ar": "غيني", "code": "GW"},
  {"id": 93, "name_en": "Guyanese", "name_ar": "غياني", "code": "GY"},
  {"id": 94, "name_en": "Haitian", "name_ar": "هايتي", "code": "HT"},
  {"id": 95, "name_en": "Heard and Mc Donald Islanders", "name_ar": "جزيرة هيرد وجزر ماكدونالد", "code": "HM"},
  {"id": 96, "name_en": "Honduran", "name_ar": "هندوراسي", "code": "HN"},
  {"id": 97, "name_en": "Hongkongese", "name_ar": "هونغ كونغي", "code": "HK"},
  {"id": 98, "name_en": "Hungarian", "name_ar": "مجري", "code": "HU"},
  {"id": 99, "name_en": "Icelandic", "name_ar": "آيسلندي", "code": "IS"},
  {"id": 100, "name_en": "Indian", "name_ar": "هندي", "code": "IN"},
  {"id": 101, "name_en": "Manx", "name_ar": "ماني", "code": "IM"},
  {"id": 102, "name_en": "Indonesian", "name_ar": "أندونيسيي", "code": "ID"},
  {"id": 103, "name_en": "Iranian", "name_ar": "إيراني", "code": "IR"},
  {"id": 104, "name_en": "Iraqi", "name_ar": "عراقي", "code": "IQ"},
  {"id": 105, "name_en": "Irish", "name_ar": "إيرلندي", "code": "IE"},
  {"id": 106, "name_en": "Italian", "name_ar": "إيطالي", "code": "IT"},
  {"id": 107, "name_en": "Ivory Coastian", "name_ar": "ساحل العاج", "code": "CI"},
  {"id": 108, "name_en": "Jersian", "name_ar": "جيرزي", "code": "JE"},
  {"id": 109, "name_en": "Jamaican", "name_ar": "جمايكي", "code": "JM"},
  {"id": 110, "name_en": "Japanese", "name_ar": "ياباني", "code": "JP"},
  {"id": 111, "name_en": "Jordanian", "name_ar": "أردني", "code": "JO"},
  {"id": 112, "name_en": "Kazakh", "name_ar": "كازاخستاني", "code": "KZ"},
  {"id": 113, "name_en": "Kenyan", "name_ar": "كيني", "code": "KE"},
  {"id": 114, "name_en": "I-Kiribati", "name_ar": "كيريباتي", "code": "KI"},
  {"id": 115, "name_en": "North Korean", "name_ar": "كوري", "code": "KP"},
  {"id": 116, "name_en": "South Korean", "name_ar": "كوري", "code": "KR"},
  {"id": 117, "name_en": "Kosovar", "name_ar": "كوسيفي", "code": "XK"},
  {"id": 118, "name_en": "Kuwaiti", "name_ar": "كويتي", "code": "KW"},
  {"id": 119, "name_en": "Kyrgyzstani", "name_ar": "قيرغيزستاني", "code": "KG"},
  {"id": 120, "name_en": "Laotian", "name_ar": "لاوسي", "code": "LA"},
  {"id": 121, "name_en": "Latvian", "name_ar": "لاتيفي", "code": "LV"},
  {"id": 122, "name_en": "Lebanese", "name_ar": "لبناني", "code": "LB"},
  {"id": 123, "name_en": "Basotho", "name_ar": "ليوسيتي", "code": "LS"},
  {"id": 124, "name_en": "Liberian", "name_ar": "ليبيري", "code": "LR"},
  {"id": 125, "name_en": "Libyan", "name_ar": "ليبي", "code": "LY"},
  {"id": 126, "name_en": "Liechtenstein", "name_ar": "ليختنشتيني", "code": "LI"},
  {"id": 127, "name_en": "Lithuanian", "name_ar": "لتوانيي", "code": "LT"},
  {"id": 128, "name_en": "Luxembourger", "name_ar": "لوكسمبورغي", "code": "LU"},
  {"id": 129, "name_en": "Sri Lankian", "name_ar": "سريلانكي", "code": "LK"},
  {"id": 130, "name_en": "Macanese", "name_ar": "ماكاوي", "code": "MO"},
  {"id": 131, "name_en": "Macedonian", "name_ar": "مقدوني", "code": "MK"},
  {"id": 132, "name_en": "Malagasy", "name_ar": "مدغشقري", "code": "MG"},
  {"id": 133, "name_en": "Malawian", "name_ar": "مالاوي", "code": "MW"},
  {"id": 134, "name_en": "Malaysian", "name_ar": "ماليزي", "code": "MY"},
  {"id": 135, "name_en": "Maldivian", "name_ar": "مالديفي", "code": "MV"},
  {"id": 136, "name_en": "Malian", "name_ar": "مالي", "code": "ML"},
  {"id": 137, "name_en": "Maltese", "name_ar": "مالطي", "code": "MT"},
  {"id": 138, "name_en": "Marshallese", "name_ar": "مارشالي", "code": "MH"},
  {"id": 139, "name_en": "Martiniquais", "name_ar": "مارتينيكي", "code": "MQ"},
  {"id": 140, "name_en": "Mauritanian", "name_ar": "موريتانيي", "code": "MR"},
  {"id": 141, "name_en": "Mauritian", "name_ar": "موريشيوسي", "code": "MU"},
  {"id": 142, "name_en": "Mahoran", "name_ar": "مايوتي", "code": "YT"},
  {"id": 143, "name_en": "Mexican", "name_ar": "مكسيكي", "code": "MX"},
  {"id": 144, "name_en": "Micronesian", "name_ar": "مايكرونيزيي", "code": "FM"},
  {"id": 145, "name_en": "Moldovan", "name_ar": "مولديفي", "code": "MD"},
  {"id": 146, "name_en": "Monacan", "name_ar": "مونيكي", "code": "MC"},
  {"id": 147, "name_en": "Mongolian", "name_ar": "منغولي", "code": "MN"},
  {"id": 148, "name_en": "Montenegrin", "name_ar": "الجبل الأسود", "code": "ME"},
  {"id": 149, "name_en": "Montserratian", "name_ar": "مونتسيراتي", "code": "MS"},
  {"id": 150, "name_en": "Moroccan", "name_ar": "مغربي", "code": "MA"},
  {"id": 151, "name_en": "Mozambican", "name_ar": "موزمبيقي", "code": "MZ"},
  {"id": 152, "name_en": "Myanmarian", "name_ar": "ميانماري", "code": "MM"},
  {"id": 153, "name_en": "Namibian", "name_ar": "ناميبي", "code": "NA"},
  {"id": 154, "name_en": "Nauruan", "name_ar": "نوري", "code": "NR"},
  {"id": 155, "name_en": "Nepalese", "name_ar": "نيبالي", "code": "NP"},
  {"id": 156, "name_en": "Dutch", "name_ar": "هولندي", "code": "NL"},
  {"id": 157, "name_en": "Dutch Antilier", "name_ar": "هولندي", "code": "AN"},
  {"id": 158, "name_en": "New Caledonian", "name_ar": "كاليدوني", "code": "NC"},
  {"id": 159, "name_en": "New Zealander", "name_ar": "نيوزيلندي", "code": "NZ"},
  {"id": 160, "name_en": "Nicaraguan", "name_ar": "نيكاراجوي", "code": "NI"},
  {"id": 161, "name_en": "Nigerien", "name_ar": "نيجيري", "code": "NE"},
  {"id": 162, "name_en": "Nigerian", "name_ar": "نيجيري", "code": "NG"},
  {"id": 163, "name_en": "Niuean", "name_ar": "ني", "code": "NU"},
  {"id": 164, "name_en": "Norfolk Islander", "name_ar": "نورفوليكي", "code": "NF"},
  {"id": 165, "name_en": "Northern Marianan", "name_ar": "ماريني", "code": "MP"},
  {"id": 166, "name_en": "Norwegian", "name_ar": "نرويجي", "code": "NO"},
  {"id": 167, "name_en": "Omani", "name_ar": "عماني", "code": "OM"},
  {"id": 168, "name_en": "Pakistani", "name_ar": "باكستاني", "code": "PK"},
  {"id": 169, "name_en": "Palauan", "name_ar": "بالاوي", "code": "PW"},
  {"id": 170, "name_en": "Palestinian", "name_ar": "فلسطيني", "code": "PS"},
  {"id": 171, "name_en": "Panamanian", "name_ar": "بنمي", "code": "PA"},
  {"id": 172, "name_en": "Papua New Guinean", "name_ar": "بابوي", "code": "PG"},
  {"id": 173, "name_en": "Paraguayan", "name_ar": "بارغاوي", "code": "PY"},
  {"id": 174, "name_en": "Peruvian", "name_ar": "بيري", "code": "PE"},
  {"id": 175, "name_en": "Filipino", "name_ar": "فلبيني", "code": "PH"},
  {"id": 176, "name_en": "Pitcairn Islander", "name_ar": "بيتكيرني", "code": "PN"},
  {"id": 177, "name_en": "Polish", "name_ar": "بوليني", "code": "PL"},
  {"id": 178, "name_en": "Portuguese", "name_ar": "برتغالي", "code": "PT"},
  {"id": 179, "name_en": "Puerto Rican", "name_ar": "بورتي", "code": "PR"},
  {"id": 180, "name_en": "Qatari", "name_ar": "قطري", "code": "QA"},
  {"id": 181, "name_en": "Reunionese", "name_ar": "ريونيوني", "code": "RE"},
  {"id": 182, "name_en": "Romanian", "name_ar": "روماني", "code": "RO"},
  {"id": 183, "name_en": "Russian", "name_ar": "روسي", "code": "RU"},
  {"id": 184, "name_en": "Rwandan", "name_ar": "رواندا", "code": "RW"},
  {"id": 185, "name_en": "", "name_ar": "Kittitian/Nevisian", "code": "KN"},
  {"id": 186, "name_en": "St. Martian(French)", "name_ar": "ساينت مارتني فرنسي", "code": "MF"},
  {"id": 187, "name_en": "St. Martian(Dutch)", "name_ar": "ساينت مارتني هولندي", "code": "SX"},
  {"id": 188, "name_en": "St. Pierre and Miquelon", "name_ar": "سان بيير وميكلوني", "code": "LC"},
  {"id": 189, "name_en": "Saint Vincent and the Grenadines", "name_ar": "سانت فنسنت وجزر غرينادين", "code": "VC"},
  {"id": 190, "name_en": "Samoan", "name_ar": "ساموي", "code": "WS"},
  {"id": 191, "name_en": "Sammarinese", "name_ar": "ماريني", "code": "SM"},
  {"id": 192, "name_en": "Sao Tomean", "name_ar": "ساو تومي وبرينسيبي", "code": "ST"},
  {"id": 193, "name_en": "Saudi Arabian", "name_ar": "سعودي", "code": "SA"},
  {"id": 194, "name_en": "Senegalese", "name_ar": "سنغالي", "code": "SN"},
  {"id": 195, "name_en": "Serbian", "name_ar": "صربي", "code": "RS"},
  {"id": 196, "name_en": "Seychellois", "name_ar": "سيشيلي", "code": "SC"},
  {"id": 197, "name_en": "Sierra Leonean", "name_ar": "سيراليوني", "code": "SL"},
  {"id": 198, "name_en": "Singaporean", "name_ar": "سنغافوري", "code": "SG"},
  {"id": 199, "name_en": "Slovak", "name_ar": "سولفاكي", "code": "SK"},
  {"id": 200, "name_en": "Slovenian", "name_ar": "سولفيني", "code": "SI"},
  {"id": 201, "name_en": "Solomon Island", "name_ar": "جزر سليمان", "code": "SB"},
  {"id": 202, "name_en": "Somali", "name_ar": "صومالي", "code": "SO"},
  {"id": 203, "name_en": "South African", "name_ar": "أفريقي", "code": "ZA"},
  {"id": 204, "name_en": "South Georgia and the South Sandwich", "name_ar": "لمنطقة القطبية الجنوبية", "code": "GS"},
  {"id": 205, "name_en": "South Sudanese", "name_ar": "سوادني جنوبي", "code": "SS"},
  {"id": 206, "name_en": "Spanish", "name_ar": "إسباني", "code": "ES"},
  {"id": 207, "name_en": "St. Helenian", "name_ar": "هيلاني", "code": "SH"},
  {"id": 208, "name_en": "Sudanese", "name_ar": "سوداني", "code": "SD"},
  {"id": 209, "name_en": "Surinamese", "name_ar": "سورينامي", "code": "SR"},
  {"id": 210, "name_en": "Svalbardian/Jan Mayenian", "name_ar": "سفالبارد ويان ماين", "code": "SJ"},
  {"id": 211, "name_en": "Swazi", "name_ar": "سوازيلندي", "code": "SZ"},
  {"id": 212, "name_en": "Swedish", "name_ar": "سويدي", "code": "SE"},
  {"id": 213, "name_en": "Swiss", "name_ar": "سويسري", "code": "CH"},
  {"id": 214, "name_en": "Syrian", "name_ar": "سوري", "code": "SY"},
  {"id": 215, "name_en": "Taiwanese", "name_ar": "تايواني", "code": "TW"},
  {"id": 216, "name_en": "Tajikistani", "name_ar": "طاجيكستاني", "code": "TJ"},
  {"id": 217, "name_en": "Tanzanian", "name_ar": "تنزانيي", "code": "TZ"},
  {"id": 218, "name_en": "Thai", "name_ar": "تايلندي", "code": "TH"},
  {"id": 219, "name_en": "Timor-Lestian", "name_ar": "تيموري", "code": "TL"},
  {"id": 220, "name_en": "Togolese", "name_ar": "توغي", "code": "TG"},
  {"id": 221, "name_en": "Tokelaian", "name_ar": "توكيلاوي", "code": "TK"},
  {"id": 222, "name_en": "Tongan", "name_ar": "تونغي", "code": "TO"},
  {"id": 223, "name_en": "Trinidadian/Tobagonian", "name_ar": "ترينيداد وتوباغو", "code": "TT"},
  {"id": 224, "name_en": "Tunisian", "name_ar": "تونسي", "code": "TN"},
  {"id": 225, "name_en": "Turkish", "name_ar": "تركي", "code": "TR"},
  {"id": 226, "name_en": "Turkmen", "name_ar": "تركمانستاني", "code": "TM"},
  {"id": 227, "name_en": "Turks and Caicos Islands", "name_ar": "جزر توركس وكايكوس", "code": "TC"},
  {"id": 228, "name_en": "Tuvaluan", "name_ar": "توفالي", "code": "TV"},
  {"id": 229, "name_en": "Ugandan", "name_ar": "أوغندي", "code": "UG"},
  {"id": 230, "name_en": "Ukrainian", "name_ar": "أوكراني", "code": "UA"},
  {"id": 231, "name_en": "Emirati", "name_ar": "إماراتي", "code": "AE"},
  {"id": 232, "name_en": "British", "name_ar": "بريطاني", "code": "GB"},
  {"id": 233, "name_en": "American", "name_ar": "أمريكي", "code": "US"},
  {"id": 234, "name_en": "US Minor Outlying Islander", "name_ar": "أمريكي", "code": "UM"},
  {"id": 235, "name_en": "Uruguayan", "name_ar": "أورغواي", "code": "UY"},
  {"id": 236, "name_en": "Uzbek", "name_ar": "أوزباكستاني", "code": "UZ"},
  {"id": 237, "name_en": "Vanuatuan", "name_ar": "فانواتي", "code": "VU"},
  {"id": 238, "name_en": "Venezuelan", "name_ar": "فنزويلي", "code": "VE"},
  {"id": 239, "name_en": "Vietnamese", "name_ar": "فيتنامي", "code": "VN"},
  {"id": 240, "name_en": "American Virgin Islander", "name_ar": "أمريكي", "code": "VI"},
  {"id": 241, "name_en": "Vatican", "name_ar": "فاتيكاني", "code": "VA"},
  {"id": 242, "name_en": "Wallisian/Futunan", "name_ar": "فوتوني", "code": "WF"},
  {"id": 243, "name_en": "Sahrawian", "name_ar": "صحراوي", "code": "EH"},
  {"id": 244, "name_en": "Yemeni", "name_ar": "يمني", "code": "YE"},
  {"id": 245, "name_en": "Zambian", "name_ar": "زامبياني", "code": "ZM"},
  {"id": 246, "name_en": "Zimbabwean", "name_ar": "زمبابوي", "code": "ZW"}
];

List degreeArr = [
  {"id": 1, "name_en": "Less than high school", "name_ar": "أقل من الثانوية"},
  {"id": 2, "name_en": "High School", "name_ar": "الدراسة الثانوية"},
  {"id": 3, "name_en": "Diploma", "name_ar": "دبلوم"},
  {"id": 4, "name_en": "Bachelor", "name_ar": "بكالوريوس"},
  {"id": 5, "name_en": "Master", "name_ar": "ماجستير"},
  {"id": 6, "name_en": "PhD", "name_ar": "دكتوراه"}
];
List currencyArr = [
  {"id": 'دينار اردني', "name_en": "JOD", "name_ar": "دينار اردني"},
  {"id": 'دولار امريكي', "name_en": "USD", "name_ar": "دولار امريكي"},
  {"id": ' يورو', "name_en": "EUR", "name_ar": "يورو"},
];

List levelArr = [
  {"id": '1', "name_en": "Beginner", "name_ar": "مبتدئ"},
  {"id": '2', "name_en": "Intermediate", "name_ar": "متوسط"},
  {"id": ' 3', "name_en": "Advanced", "name_ar": "متقدم"},
];

List maritalStatusArr = [
  {"id": '1', "name_en": "Single", "name_ar": "اعزب/عزباء"},
  {"id": '2', "name_en": "Married", "name_ar": "متزوج/ة"},
  {"id": '3', "name_en": "Divorced", "name_ar": "مطلق/ة"},
  {"id": '4', "name_en": "Widowed", "name_ar": "أرمل/ة"},
];
List workNatureArr = [
  {"id": '1', "name_en": 'Work from home "remotely"', "name_ar": 'العمل من المنزل " عن بعد"'},
  {"id": '2', "name_en": 'Work within the company', "name_ar": 'العمل داخل الشركة'},
  {"id": '3', "name_en": 'Freelance work', "name_ar": 'عمل حر freelance'},
];
List contractDurationArr = [
  {"id": '1', "name_en": 'Monthly', "name_ar": 'شهري'},
  {"id": '2', "name_en": 'Annual', "name_ar": 'سنوي'},
  {"id": '3', "name_en": 'Without contract', "name_ar": 'بدون عقد'},
  {"id": '4', "name_en": '3 months', "name_ar": '٣ اشهر'},
  {"id": '5', "name_en": '6 months', "name_ar": '٦ اشهر'},
  {"id": '6', "name_en": 'Two years', "name_ar": 'سنتين'},
  {"id": '7', "name_en": 'Undefined', "name_ar": 'غير محدد'},
  {"id": '8', "name_en": 'Training', "name_ar": 'تدريب'},
  {"id": '9', "name_en": 'Volunteering', "name_ar": 'تطوع'},
];
List workingHoursArr = [
  {"id": '1', "name_en": 'Morning Part', "name_ar": 'جزئي صباحي'},
  {"id": '2', "name_en": 'Evening Part', "name_ar": 'جزئي مسائي'},
  {"id": '3', "name_en": 'Full-time', "name_ar": 'دوام كامل'},
  {"id": '4', "name_en": 'Remote Work (Home)', "name_ar": 'دوام عند بعد ( منزلي)'},
  {"id": '5', "name_en": 'Field With Salary', "name_ar": 'ميداني براتب'},
  {"id": '6', "name_en": 'Commission system without fixed working hours', "name_ar": 'نظام عمولة دون ساعات عمل محددة'},
];
List insuranceArr = [
  {"id": '1', "name_en": 'Full insurance', "name_ar": 'تأمين شامل'},
  {"id": '2', "name_en": 'Third party insurance', "name_ar": 'تأمين ضد الغير'},
  {"id": '3', "name_en": 'There is no insurance', "name_ar": 'لا يوجد تامين'},
  {"id": '4', "name_en": 'Private Insurance', "name_ar": 'تامين خاص'},
];
List salaryArr = [
  {"id": '1', "name_en": 'Monthly salary', "name_ar": 'راتب شهري'},
  {"id": '2', "name_en": 'Commission system', "name_ar": 'نظام العمولة'},
  {"id": '2', "name_en": 'Payment As Per App', "name_ar": 'الدفع حسب التطبيق'},
  {"id": '2', "name_en": 'Daily Wages', "name_ar": 'اجور مياومة'},
];
List workTypeArr = [
  {"id": '1', "name_en": 'Protection of important individuals and personalities', "name_ar": 'حماية افراد و شخصيات مهمة'},
  {"id": '2', "name_en": 'Protection of corporate headquarters and field work sites', "name_ar": 'حماية مقرات شركات و مواقع عمل ميدانية'},
  {"id": '3', "name_en": 'Protection of banks, malls, governmental and private banks', "name_ar": 'حماية البنوك والمولات و المصارف الحكوميةو الأهلية'},
  {"id": '4', "name_en": 'Protection of shops, malls, stores and warehouses', "name_ar": 'حماية المحلات التجارية و المولات والمخازن و المستودعات'},
  {"id": '5', "name_en": 'Protection of university and school buildings', "name_ar": 'حماية الابنية الجامعة و المدرسية'},
  {"id": '6', "name_en": 'Protection of Arab and foreign embassies, attachés and international organizations', "name_ar": 'حماية السفارات العربية و الاجنبية و الملحقيات و المنظمات الدولية'},
  {"id": '7', "name_en": 'Home protection', "name_ar": 'حماية المنازل'},
  {"id": '8', "name_en": 'Factories and farm protection', "name_ar": 'حماية المصانع و المزارع'},
  {"id": '9', "name_en": 'Security and protection consultant', "name_ar": 'تقديم استشارات امن وحماية'},
  {"id": '10', "name_en": 'Protection of electric power stations, water wells and oil installations', "name_ar": 'حماية محطات الطاقة الكهربائية و ابار المياه و منشأت النفطية'},
  {"id": '11', "name_en": 'All the above', "name_ar": 'جميع ما ذكر'},
  {"id": '12', "name_en": 'Undefined', "name_ar": 'غير معرف'},
];

List previousWorkArr = [
  {"id": '1', "name_en": 'Arab Army', "name_ar": 'الجيش العربي'},
  {"id": '2', "name_en": 'Public Security', "name_ar": 'الأمن العام'},
  {"id": '3', "name_en": 'Civil Defense', "name_ar": 'الدفاع المدني'},
  {"id": '4', "name_en": 'Gendarmerie', "name_ar": 'الدرك'},
  {"id": '5', "name_en": 'Intelligence Agency', "name_ar": 'المخابرات'},
  {"id": '6', "name_en": 'Undefined', "name_ar": 'غير معرف'},
];

List rankArr = [
  {"id": '1', "name_en": 'Second soldier', "name_ar": 'جندي ثاني'},
  {"id": '2', "name_en": 'First soldier', "name_ar": 'جندي اول'},
  {"id": '3', "name_en": 'Corporal', "name_ar": 'عريف'},
  {"id": '4', "name_en": 'Sergeant', "name_ar": 'رقيب'},
  {"id": '5', "name_en": 'Staff Sergeant', "name_ar": 'رقيب اول'},
  {"id": '6', "name_en": 'Agent', "name_ar": 'وكيل'},
  {"id": '7', "name_en": 'First Agent', "name_ar": 'وكيل اول'},
  {"id": '8', "name_en": 'Field Marshal', "name_ar": 'مشير'},
  {"id": '9', "name_en": 'First Team', "name_ar": 'فريق اول'},
  {"id": '10', "name_en": 'Team', "name_ar": 'فريق'},
  {"id": '11', "name_en": 'Brigade', "name_ar": 'لواء'},
  {"id": '12', "name_en": 'General', "name_ar": 'عميد'},
  {"id": '13', "name_en": 'Colonel', "name_ar": 'عقيد'},
  {"id": '14', "name_en": 'Lieutenant colonel', "name_ar": 'مقدم'},
  {"id": '15', "name_en": 'Pioneer', "name_ar": 'رائد'},
  {"id": '16', "name_en": 'Captain', "name_ar": 'نقيب'},
  {"id": '17', "name_en": 'First Lieutenant', "name_ar": 'ملازم أول'},
  {"id": '18', "name_en": 'Lieutenant', "name_ar": 'ملازم'},
  {"id": '19', "name_en": 'Undefined', "name_ar": 'غير معرف'},
];

List currentStatusArr = [
  {"id": '1', "name_en": 'unemployed', "name_ar": 'عاطل عن العمل'},
  {"id": '2', "name_en": 'Currently a government employee', "name_ar": 'موظف حكومي'},
  {"id": '3', "name_en": 'Currently a private sector employee', "name_ar": 'موظف قطاع خاص'},
  {"id": '4', "name_en": 'Free businees', "name_ar": 'الاعمال الحره'},
  {"id": '5', "name_en": 'Day laborer', "name_ar": 'عامل مياومة'},
];
List computerSkillsArr = [
  {"id": '1', "name_en": 'Beginner', "name_ar": 'مبتدئ'},
  {"id": '2', "name_en": 'Intermediate', "name_ar": 'متوسط'},
  {"id": '3', "name_en": 'Above Avarage', "name_ar": 'فوق المتوسط'},
  {"id": '4', "name_en": 'Advanced', "name_ar": 'متقدم'},
  {"id": '5', "name_en": 'Very Advanced', "name_ar": 'متقدم جداً'},
];
List englishLevelArr = [
  {"id": '1', "name_en": 'Beginner', "name_ar": 'مبتدئ'},
  {"id": '2', "name_en": 'Intermediate', "name_ar": 'متوسط'},
  {"id": '3', "name_en": 'Above Avarage', "name_ar": 'فوق المتوسط'},
  {"id": '4', "name_en": 'Advanced', "name_ar": 'متقدم'},
  {"id": '5', "name_en": 'Very Advanced', "name_ar": 'متقدم جداً'},
];
List genderArr = [
  {"id": '1', "name_en": 'Male', "name_ar": 'ذكر'},
  {"id": '2', "name_en": 'Female', "name_ar": 'انثى'},
  {"id": '3', "name_en": 'Any', "name_ar": 'كلاهما'},
  {"id": '4', "name_en": 'Undefined', "name_ar": 'غير محدد'},
];
List reportArr = [
  {"id": '1', "name_en": 'Fake Job Advertisement', "name_ar": 'اعلان وظيفة مزيف'},
  {"id": '2', "name_en": 'Unclear Job Advertisement', "name_ar": 'اعلان وظيفة غير واضح'},
  {"id": '3', "name_en": 'Technical Issue', "name_ar": 'هناك مشكلة فنية'},
];

List fiveArr = [
  {"id": '5', "name_en": '5', "name_ar": '5'},
  {"id": '10', "name_en": '10', "name_ar": '10'},
  {"id": '15', "name_en": '15', "name_ar": '15'},
  {"id": '20', "name_en": '20', "name_ar": '20'},
  {"id": '25', "name_en": '25', "name_ar": '25'},
  {"id": '30', "name_en": '30', "name_ar": '30'},
  {"id": '35', "name_en": '35', "name_ar": '35'},
  {"id": '40', "name_en": '40', "name_ar": '40'},
  {"id": '45', "name_en": '45', "name_ar": '45'},
  {"id": '50', "name_en": '50', "name_ar": '50'},
  {"id": '55', "name_en": '55', "name_ar": '55'},
  {"id": '60', "name_en": '60', "name_ar": '60'},
  {"id": '65', "name_en": '65', "name_ar": '65'},
  {"id": '70', "name_en": '70', "name_ar": '70'},
  {"id": '75', "name_en": '75', "name_ar": '75'},
  {"id": '80', "name_en": '80', "name_ar": '80'},
  {"id": '85', "name_en": '85', "name_ar": '85'},
  {"id": '90', "name_en": '90', "name_ar": '90'},
  {"id": '95', "name_en": '95', "name_ar": '95'},
  {"id": '100', "name_en": '100', "name_ar": '100'}
];
List sortArr = [
  {"id": '1', "name_en": 'Deadline - Descending', "name_ar": 'تاريخ نهاية التقديم - من الاقدم الى الاحدث'},
  {"id": '2', "name_en": 'Dealine - Ascending', "name_ar": 'تاريخ نهاية التقديم - من الاحدث الى الاقدم'},
  {"id": '3', "name_en": 'Oldest first', "name_ar": 'تاريخ النشر من الاقدم الى الاحدث'},
  {"id": '4', "name_en": 'Newest first', "name_ar": 'تاريخ النشر من الاحدث الى الاقدم'},
];
List yesNo = [
  {"id": '1', "name_en": 'Yes', "name_ar": 'نعم'},
  {"id": '2', "name_en": 'No', "name_ar": 'لا'},
];
List averageTypeArr = [
  {"id": '1', "name_en": 'Percentage (0-100%)', "name_ar": '(0-100%) نسبة مئوية'},
  {"id": '2', "name_en": 'Estimation (1,2,3,4)', "name_ar": 'تقريب (1,2,3,4)'},
  {"id": '3', "name_en": 'Points (1 - 4)', "name_ar": 'نقاط (1 - 4)'},
];
List workshopSizeArr = [
  {"id": '1', "name_en": 'Small Workshops', "name_ar": 'ورشات صغيرة'},
  {"id": '2', "name_en": 'Medium Workshops', "name_ar": 'ورشات متوسطة'},
  {"id": '3', "name_en": 'Big Workshops', "name_ar": 'ورشات كبيرة'},
];
List fuelTypeArr = [
  {"id": '1', "name_en": 'Diesel', "name_ar": 'ديزل'},
  {"id": '2', "name_en": 'Petrol', "name_ar": 'بنزين'},
  {"id": '3', "name_en": 'Electricity', "name_ar": 'كهرباء'},
  {"id": '4', "name_en": 'Hybrid', "name_ar": 'هايبرد'},
];
List professionalRankArr = [
  {"id": '1', "name_en": 'Professional', "name_ar": 'معلم'},
  {"id": '2', "name_en": 'Professional Assistant', "name_ar": 'مساعد معلم'},
  {"id": '3', "name_en": 'Technical', "name_ar": 'فني'},
  {"id": '4', "name_en": 'Trainee', "name_ar": 'متدرب'},
  {"id": '5', "name_en": 'No experience', "name_ar": 'لا تمتلك خبرة'},
];
List conditionArr = [
  {"id": '1', "name_en": 'Excellent', "name_ar": 'ممتازة'},
  {"id": '2', "name_en": 'Good', "name_ar": 'جيدة'},
  {"id": '3', "name_en": 'Medium', "name_ar": 'متوسطة'},
  {"id": '4', "name_en": 'Bad', "name_ar": 'سيئة'},
  {"id": '5', "name_en": 'Very Bad', "name_ar": 'سيئة جدا'},
];
List transportServiceTypeArr = [
  {"id": '1', "name_en": 'Work In Delivery of Goods', "name_ar": 'العمل في توصيل بضائع'},
  {"id": '2', "name_en": 'Work in Passenger Transport', "name_ar": 'العمل في نقل الركاب'},
  {"id": '3', "name_en": 'Working in a Restaurant Delivery Service', "name_ar": 'في خدمة توصيل المطاعم'},
  {"id": '4', "name_en": 'No Specific Field', "name_ar": 'لا يوجد مجال محدد'},
];
List languageArr = [
   {"id": 1, "name_ar": "الإنجليزية", "name_en": "English"},
  {"id": 2, "name_ar": "العربية", "name_en": "Arabic"},
  {"id": 3, "name_ar": "الأفريقانية", "name_en": "Afrikaans"},
  {"id": 4, "name_ar": "الألبانية", "name_en": "Albanian"},
  {"id": 5, "name_ar": "الأمهرية", "name_en": "Amharic"},
  {"id": 6, "name_ar": "الارمنية", "name_en": "Armenian"},
  {"id": 7, "name_ar": "الأذرية", "name_en": "Azerbaijani"},
  {"id": 8, "name_ar": "الباسكية", "name_en": "Basque"},
  {"id": 9, "name_ar": "البيلاروسية", "name_en": "Belarusian"},
  {"id": 10, "name_ar": "البنغالية", "name_en": "Bengali"},
  {"id": 11, "name_ar": "البوسنية", "name_en": "Bosnian"},
  {"id": 12, "name_ar": "البلغارية", "name_en": "Bulgarian"},
  {"id": 13, "name_ar": "القطلونية", "name_en": "Catalan"},
  {"id": 14, "name_ar": "السيبيوانية", "name_en": "Cebuano"},
  {"id": 15, "name_ar": "تشيتشوا", "name_en": "Chichewa"},
  {"id": 16, "name_ar": "الصينية (المبسطة)", "name_en": "Chinese"},
  {"id": 17, "name_ar": "الصينية (التقليدية)", "name_en": "Chinese (traditional)"},
  {"id": 18, "name_ar": "الكورسيكي", "name_en": "Corsican"},
  {"id": 19, "name_ar": "الكرواتية", "name_en": "Croatian"},
  {"id": 20, "name_ar": "التشيكية", "name_en": "Czech"},
  {"id": 21, "name_ar": "الدانماركية", "name_en": "Danish"},
  {"id": 22, "name_ar": "الهولندية", "name_en": "Dutch"},
  {"id": 23, "name_ar": "الاسبرانتو", "name_en": "Esperanto"},
  {"id": 24, "name_ar": "الإستونية", "name_en": "Estonian"},
  {"id": 25, "name_ar": "الفلبينية", "name_en": "Filipino"},
  {"id": 26, "name_ar": "الفنلندية", "name_en": "Finnish"},
  {"id": 27, "name_ar": "الفرنسية", "name_en": "French"},
  {"id": 28, "name_ar": "الفريزية", "name_en": "Frisian"},
  {"id": 29, "name_ar": "الجاليكية", "name_en": "Galician"},
  {"id": 30, "name_ar": "الجورجية", "name_en": "Georgian"},
  {"id": 31, "name_ar": "الألمانية", "name_en": "German"},
  {"id": 32, "name_ar": "اليونانية", "name_en": "Greek"},
  {"id": 33, "name_ar": "الغوجراتية", "name_en": "Gujarati"},
  {"id": 34, "name_ar": "اللغة الكريولية الهايتية", "name_en": "Haitian Creole"},
  {"id": 35, "name_ar": "الهوسا", "name_en": "Hausa"},
  {"id": 36, "name_ar": "لغة هاواي", "name_en": "Hawaiian"},
  {"id": 37, "name_ar": "العبرية", "name_en": "Hebrew"},
  {"id": 38, "name_ar": "الهندية", "name_en": "Hindi"},
  {"id": 39, "name_ar": "الهمونجية", "name_en": "Hmong"},
  {"id": 40, "name_ar": "الهنغارية", "name_en": "Hungarian"},
  {"id": 41, "name_ar": "الآيسلندية", "name_en": "Icelandic"},
  {"id": 42, "name_ar": "الإيغبو", "name_en": "Igbo"},
  {"id": 43, "name_ar": "الإندونيسية", "name_en": "Indonesian"},
  {"id": 44, "name_ar": "الأيرلندية", "name_en": "Irish"},
  {"id": 45, "name_ar": "الإيطالية", "name_en": "Italian"},
  {"id": 46, "name_ar": "ياباني", "name_en": "Japanese"},
  {"id": 47, "name_ar": "الجاوية", "name_en": "Javanese"},
  {"id": 48, "name_ar": "الكانادا", "name_en": "Kannada"},
  {"id": 49, "name_ar": "الكازاكي", "name_en": "Kazakh"},
  {"id": 50, "name_ar": "الخميرية", "name_en": "Khmer"},
  {"id": 51, "name_ar": "الكينيارواندية", "name_en": "Kinyarwanda"},
  {"id": 52, "name_ar": "الكورية", "name_en": "Korean"},
  {"id": 53, "name_ar": "الكردية", "name_en": "Kurdish (Kurmanji)"},
  {"id": 54, "name_ar": "القيرغيزية", "name_en": "Kyrgyz"},
  {"id": 55, "name_ar": "اللاوو", "name_en": "Lao"},
  {"id": 56, "name_ar": "اللاتينية", "name_en": "Latin"},
  {"id": 57, "name_ar": "اللاتفية", "name_en": "Latvian"},
  {"id": 58, "name_ar": "الليتوانية", "name_en": "Lithuanian"},
  {"id": 59, "name_ar": "اللوكسمبورغية", "name_en": "Luxembourgish"},
  {"id": 60, "name_ar": "المقدونية", "name_en": "Macedonian"},
  {"id": 61, "name_ar": "المدغشقرية", "name_en": "Malagasy"},
  {"id": 62, "name_ar": "الملايو", "name_en": "Malay"},
  {"id": 63, "name_ar": "المالايالامية", "name_en": "Malayalam"},
  {"id": 64, "name_ar": "المالطيّة", "name_en": "Maltese"},
  {"id": 65, "name_ar": "الماورية", "name_en": "Maori"},
  {"id": 66, "name_ar": "المهراتية", "name_en": "Marathi"},
  {"id": 67, "name_ar": "الاسكتلندية الغالية", "name_en": "Scots Gaelic"},
  {"id": 81, "name_ar": "الصربية", "name_en": "Serbian"},
  {"id": 82, "name_ar": "السيسوتو", "name_en": "Sesotho"},
  {"id": 83, "name_ar": "الشونا", "name_en": "Shona"},
  {"id": 84, "name_ar": "السندية", "name_en": "Sindhi"},
  {"id": 85, "name_ar": "السنهالية", "name_en": "Sinhala"},
  {"id": 86, "name_ar": "السلوفاكية", "name_en": "Slovak"},
  {"id": 87, "name_ar": "السلوفينية", "name_en": "Slovenian"},
  {"id": 88, "name_ar": "الصومالية", "name_en": "Somali"},
  {"id": 89, "name_ar": "الإسبانية", "name_en": "Spanish"},
  {"id": 90, "name_ar": "الساندينيزية", "name_en": "Sundanese"},
  {"id": 91, "name_ar": "السواحيلية", "name_en": "Swahili"},
  {"id": 92, "name_ar": "السويدية", "name_en": "Swedish"},
  {"id": 93, "name_ar": "الطاجيكي", "name_en": "Tajik"},
  {"id": 94, "name_ar": "التاميلية", "name_en": "Tamil"},
  {"id": 95, "name_ar": "التتارية", "name_en": "Tatar"},
  {"id": 96, "name_ar": "التيلوجو", "name_en": "Telugu"},
  {"id": 97, "name_ar": "التايلاندية", "name_en": "Thai"},
  {"id": 98, "name_ar": "التركية", "name_en": "Turkish"},
  {"id": 99, "name_ar": "التركمانية", "name_en": "Turkmen"},
  {"id": 100, "name_ar": "الأوكرانية", "name_en": "Ukrainian"},
  {"id": 101, "name_ar": "الأردية", "name_en": "Urdu"},
  {"id": 102, "name_ar": "الأويغورية", "name_en": "Uyghur"},
  {"id": 103, "name_ar": "الأوزبكية", "name_en": "Uzbek"},
  {"id": 104, "name_ar": "الفيتنامية", "name_en": "Vietnamese"},
  {"id": 105, "name_ar": "الويلزية", "name_en": "Welsh"},
  {"id": 106, "name_ar": "الخؤوصا", "name_en": "Xhosa"},
  {"id": 107, "name_ar": "الييدية", "name_en": "Yiddish"},
  {"id": 108, "name_ar": "اليورباية", "name_en": "Yoruba"},
  {"id": 109, "name_ar": "الزولوية", "name_en": "Zulu"}
];
// List languageArr = [
//   {'id': 'ar', 'name_en': 'Arabic', 'name_ar': 'العربية'},
//   {'id': 'en', 'name_en': 'English', 'name_ar': 'الإنجليزية'},
//   {'id': 'af', 'name_en': 'Afrikaans', 'name_ar': 'الأفريقانية'},
//   {'id': 'am', 'name_en': 'Amharic', 'name_ar': 'الأمهرية'},
//   {'id': 'az', 'name_en': 'Azerbaijani', 'name_ar': 'الأذرية'},
//   {'id': 'be', 'name_en': 'Belarusian', 'name_ar': 'البيلاروسية'},
//   {'id': 'bg', 'name_en': 'Bulgarian', 'name_ar': 'البلغارية'},
//   {'id': 'bn', 'name_en': 'Bengali', 'name_ar': 'البنغالية'},
//   {'id': 'bs', 'name_en': 'Bosnian', 'name_ar': 'البوسنية'},
//   {'id': 'ca', 'name_en': 'Catalan', 'name_ar': 'القطلونية'},
//   {'id': 'ceb', 'name_en': 'Cebuano', 'name_ar': 'السيبيوانية'},
//   {'id': 'co', 'name_en': 'Corsican', 'name_ar': 'الكورسيكي'},
//   {'id': 'cs', 'name_en': 'Czech', 'name_ar': 'التشيكية'},
//   {'id': 'cy', 'name_en': 'Welsh', 'name_ar': 'الويلزية'},
//   {'id': 'da', 'name_en': 'Danish', 'name_ar': 'الدانماركية'},
//   {'id': 'de', 'name_en': 'German', 'name_ar': 'الألمانية'},
//   {'id': 'el', 'name_en': 'Greek', 'name_ar': 'اليونانية'},
//   {'id': 'eo', 'name_en': 'Esperanto', 'name_ar': 'الاسبرانتو'},
//   {'id': 'es', 'name_en': 'Spanish', 'name_ar': 'الإسبانية'},
//   {'id': 'et', 'name_en': 'Estonian', 'name_ar': 'الإستونية'},
//   {'id': 'eu', 'name_en': 'Basque', 'name_ar': 'الباسكية'},
//   {'id': 'fa', 'name_en': 'Persian', 'name_ar': 'الفارسية'},
//   {'id': 'fi', 'name_en': 'Finnish', 'name_ar': 'الفنلندية'},
//   {'id': 'fr', 'name_en': 'French', 'name_ar': 'الفرنسية'},
//   {'id': 'fy', 'name_en': 'Frisian', 'name_ar': 'الفريزية'},
//   {'id': 'ga', 'name_en': 'Irish', 'name_ar': 'الأيرلندية'},
//   {'id': 'gd', 'name_en': 'Scots Gaelic', 'name_ar': 'الاسكتلندية الغالية'},
//   {'id': 'gl', 'name_en': 'Galician', 'name_ar': 'الجاليكية'},
//   {'id': 'gu', 'name_en': 'Gujarati', 'name_ar': 'الغوجراتية'},
//   {'id': 'ha', 'name_en': 'Hausa', 'name_ar': 'الهوسا'},
//   {'id': 'haw', 'name_en': 'Hawaiian', 'name_ar': 'لغة هاواي'},
//   {'id': 'hi', 'name_en': 'Hindi', 'name_ar': 'الهندية'},
//   {'id': 'hmn', 'name_en': 'Hmong', 'name_ar': 'الهمونجية'},
//   {'id': 'hr', 'name_en': 'Croatian', 'name_ar': 'الكرواتية'},
//   {'id': 'ht', 'name_en': 'Haitian Creole', 'name_ar': 'اللغة الكريولية الهايتية'},
//   {'id': 'hu', 'name_en': 'Hungarian', 'name_ar': 'الهنغارية'},
//   {'id': 'hy', 'name_en': 'Armenian', 'name_ar': 'الارمنية'},
//   {'id': 'id', 'name_en': 'Indonesian', 'name_ar': 'الإندونيسية'},
//   {'id': 'ig', 'name_en': 'Igbo', 'name_ar': 'الإيغبو'},
//   {'id': 'is', 'name_en': 'Icelandic', 'name_ar': 'الآيسلندية'},
//   {'id': 'it', 'name_en': 'Italian', 'name_ar': 'الإيطالية'},
//   {'id': 'iw', 'name_en': 'Hebrew', 'name_ar': 'العبرية'},
//   {'id': 'ja', 'name_en': 'Japanese', 'name_ar': 'ياباني'},
//   {'id': 'jw', 'name_en': 'Javanese', 'name_ar': 'الجاوية'},
//   {'id': 'ka', 'name_en': 'Georgian', 'name_ar': 'الجورجية'},
//   {'id': 'kk', 'name_en': 'Kazakh', 'name_ar': 'الكازاكي'},
//   {'id': 'km', 'name_en': 'Khmer', 'name_ar': 'الخميرية'},
//   {'id': 'kn', 'name_en': 'Kannada', 'name_ar': 'الكانادا'},
//   {'id': 'ko', 'name_en': 'Korean', 'name_ar': 'الكورية'},
//   {'id': 'ku', 'name_en': 'Kurdish (Kurmanji)', 'name_ar': 'الكردية'},
//   {'id': 'ky', 'name_en': 'Kyrgyz', 'name_ar': 'القيرغيزية'},
//   {'id': 'la', 'name_en': 'Latin', 'name_ar': 'اللاتينية'},
//   {'id': 'lb', 'name_en': 'Luxembourgish', 'name_ar': 'اللوكسمبورغية'},
//   {'id': 'lo', 'name_en': 'Lao', 'name_ar': 'اللاوو'},
//   {'id': 'lt', 'name_en': 'Lithuanian', 'name_ar': 'الليتوانية'},
//   {'id': 'lv', 'name_en': 'Latvian', 'name_ar': 'اللاتفية'},
//   {'id': 'mg', 'name_en': 'Malagasy', 'name_ar': 'المدغشقرية'},
//   {'id': 'mi', 'name_en': 'Maori', 'name_ar': 'الماورية'},
//   {'id': 'mk', 'name_en': 'Macedonian', 'name_ar': 'المقدونية'},
//   {'id': 'ml', 'name_en': 'Malayalam', 'name_ar': 'المالايالامية'},
//   {'id': 'mn', 'name_en': 'Mongolian', 'name_ar': 'المنغولية'},
//   {'id': 'mr', 'name_en': 'Marathi', 'name_ar': 'المهراتية'},
//   {'id': 'ms', 'name_en': 'Malay', 'name_ar': 'الملايو'},
//   {'id': 'mt', 'name_en': 'Maltese', 'name_ar': 'المالطيّة'},
//   {'id': 'my', 'name_en': 'Myanmar (Burmese)', 'name_ar': 'البورمية'},
//   {'id': 'ne', 'name_en': 'Nepali', 'name_ar': 'النيبالية'},
//   {'id': 'nl', 'name_en': 'Dutch', 'name_ar': 'الهولندية'},
//   {'id': 'no', 'name_en': 'Norwegian', 'name_ar': 'النرويجية'},
//   {'id': 'ny', 'name_en': 'Chichewa', 'name_ar': 'تشيتشوا'},
//   {'id': 'or', 'name_en': 'Odia (Oriya)', 'name_ar': 'الأوديا (الأوريا)'},
//   {'id': 'pa', 'name_en': 'Punjabi', 'name_ar': 'البنجابية'},
//   {'id': 'pl', 'name_en': 'Polish', 'name_ar': 'البولندية'},
//   {'id': 'ps', 'name_en': 'Pashto', 'name_ar': 'الباشتوية'},
//   {'id': 'pt', 'name_en': 'Portuguese', 'name_ar': 'البرتغالية'},
//   {'id': 'ro', 'name_en': 'Romanian', 'name_ar': 'الرومانية'},
//   {'id': 'ru', 'name_en': 'Russian', 'name_ar': 'الروسية'},
//   {'id': 'rw', 'name_en': 'Kinyarwanda', 'name_ar': 'الكينيارواندية'},
//   {'id': 'sd', 'name_en': 'Sindhi', 'name_ar': 'السندية'},
//   {'id': 'si', 'name_en': 'Sinhala', 'name_ar': 'السنهالية'},
//   {'id': 'sk', 'name_en': 'Slovak', 'name_ar': 'السلوفاكية'},
//   {'id': 'sl', 'name_en': 'Slovenian', 'name_ar': 'السلوفينية'},
//   {'id': 'sm', 'name_en': 'Samoan', 'name_ar': 'الساموانية'},
//   {'id': 'sn', 'name_en': 'Shona', 'name_ar': 'الشونا'},
//   {'id': 'so', 'name_en': 'Somali', 'name_ar': 'الصومالية'},
//   {'id': 'sq', 'name_en': 'Albanian', 'name_ar': 'الألبانية'},
//   {'id': 'sr', 'name_en': 'Serbian', 'name_ar': 'الصربية'},
//   {'id': 'st', 'name_en': 'Sesotho', 'name_ar': 'السيسوتو'},
//   {'id': 'su', 'name_en': 'Sundanese', 'name_ar': 'الساندينيزية'},
//   {'id': 'sv', 'name_en': 'Swedish', 'name_ar': 'السويدية'},
//   {'id': 'sw', 'name_en': 'Swahili', 'name_ar': 'السواحيلية'},
//   {'id': 'ta', 'name_en': 'Tamil', 'name_ar': 'التاميلية'},
//   {'id': 'te', 'name_en': 'Telugu', 'name_ar': 'التيلوجو'},
//   {'id': 'tg', 'name_en': 'Tajik', 'name_ar': 'الطاجيكي'},
//   {'id': 'th', 'name_en': 'Thai', 'name_ar': 'التايلاندية'},
//   {'id': 'tk', 'name_en': 'Turkmen', 'name_ar': 'التركمانية'},
//   {'id': 'tl', 'name_en': 'Filipino', 'name_ar': 'الفلبينية'},
//   {'id': 'tr', 'name_en': 'Turkish', 'name_ar': 'التركية'},
//   {'id': 'tt', 'name_en': 'Tatar', 'name_ar': 'التتارية'},
//   {'id': 'ug', 'name_en': 'Uyghur', 'name_ar': 'الأويغورية'},
//   {'id': 'uk', 'name_en': 'Ukrainian', 'name_ar': 'الأوكرانية'},
//   {'id': 'ur', 'name_en': 'Urdu', 'name_ar': 'الأردية'},
//   {'id': 'uz', 'name_en': 'Uzbek', 'name_ar': 'الأوزبكية'},
//   {'id': 'vi', 'name_en': 'Vietnamese', 'name_ar': 'الفيتنامية'},
//   {'id': 'xh', 'name_en': 'Xhosa', 'name_ar': 'الخؤوصا'},
//   {'id': 'yi', 'name_en': 'Yiddish', 'name_ar': 'الييدية'},
//   {'id': 'yo', 'name_en': 'Yoruba', 'name_ar': 'اليورباية'},
//   {'id': 'zh-CN', 'name_en': 'Chinese', 'name_ar': 'الصينية (المبسطة)'},
//   {'id': 'zh-TW', 'name_en': 'Chinese (traditional)', 'name_ar': 'الصينية (التقليدية)'},
//   {'id': 'zu', 'name_en': 'Zulu', 'name_ar': 'الزولوية'},
// ];
